### ISSUE TITLE
training data and preprocessor in method

### ISSUE THREAD

**Issue by liutianling** [saman-azhar/multilingual-sentiment-classifier#1]
Thanks for your great work!
I am learning it.
Here I have some question.

line 7 in method.py 
import preprocessor as p
I can't find where is the preprocessor ?

Anyway, can you share the training data?

Thanks very much!

**Comment by saman-azhar** [comment]
Hi, you can try directly installing the library
https://pypi.org/project/multilingual-sentiment-classifier/  and let me
know your feedback.
